sip:
  client:
    enabled: true
    domain: 127.0.0.1
    keepAliveInterval: 1m
    maxRetries: 3
    retryDelay: 5s
    registerExpires: 3600
    clientId: "34020000001320000001"
    clientName: "GB28181-Client"
